const DEMO_DATA_ACTION_TYPES = {
  FETCH_DEMO_DATA_ACTION: 'FETCH_DEMO_DATA_ACTION',
  FETCH_DEMO_DATA_ACTION_SUCCESS: 'FETCH_DEMO_DATA_ACTION_SUCCESS',
  FETCH_DEMO_DATA_ACTION_FAILURE: 'FETCH_DEMO_DATA_ACTION_FAILURE'
};

export default DEMO_DATA_ACTION_TYPES;