const DIALOG_ACTION_TYPES = {
  OPEN: '[UI_STATE]-OPEN_DIALOG',
  CLOSE: '[UI_STATE]-CLOSE_DIALOG',
  CLOSE_ALL: '[UI_STATE]-CLOSE_ALL_DIALOGS'
};

const UI_ACTION_TYPES = {
  UPDATE_SELECTED_UI_LANGUAGE: '[UI_STATE]-UPDATE_SELECTED_UI_LANGUAGE',
  UPDATE_SELECTED_UI_THEME: '[UI_STATE]-UPDATE_SELECTED_UI_THEME',
  EXPAND_MAIN_SIDEBAR: '[UI_STATE]-EXPAND_MAIN_SIDEBAR',
  COLLAPSE_MAIN_SIDEBAR: '[UI_STATE]-COLLAPSE_MAIN_SIDEBAR',
  DIALOGS: DIALOG_ACTION_TYPES
};

export default UI_ACTION_TYPES;
