export const FONT_BASE = 16;

export const VIEWPORTS = {
  MOBILE: 600,
  LAPTOP: 601,
  DESKTOP: 1200
};

export const DESKTOP_MAIN_CONTENT_WIDTH = 1052;

export const COLORS = {
  GLOBAL_WHITE: '#fff',
  GLOBAL_YELLOW: '#ff0',
  GOLD_COIN: '#fde68a',
  BACK_DROP: 'rgba(0, 0, 0, .5)',
  MAIN_CONTENT_WRAPPER_BACKGROUND: 'linear-gradient(rgb(125, 31, 214), rgb(96, 101, 251))',
  GLOBAL_BLACK: '#000',
  GLOBAL_RED: 'red',
  BORDER_COLOR: '#ebeef5',

  SIDEBAR_ITEM_BORDER: '#414141',
  DROPDOWN_BOX_SHADOW: 'rgba(0, 0, 0, .1)',
  DROPDOWN_TEXT: '#606266',
  DROPDOWN_ITEM_HOVER_BACKGROUND: '#ecf5ff',
  DROPDOWN_ITEM_HOVER_TEXT: '#66b1ff',
  SIDEBAR_BACKGROUND: '#1f1f1f',
  SIDEBAR_USER_BALANCE_INFO_WRAPPER: '#2c2a2b',
  DIALOG_BACKGROUND: '#322f30',
  DIVIDEND_ITEM_LEFT_BACKGROUND: '#242424',
  POSSIBLE_DIVIDEND_INCOME_TITLE: '#9b9b9b',
  DIALOG_ACTIVE_BUTTON_SHADOW: '#6d491f',
  DIVIDEND_FREEZE_TAB_INPUT_BORDER: '#928348',
  MAIN_BANNER_BUTTON_ACTIVATED_COLOR: '#414bb1',
  MAIN_BANNER_WARNING_TEXT: '#e9e8e8',
  SMART_CONTRACT_COMPONENT_BACKGROUND: '#8667fc',
  INVESTMENT_PLANS_WRAPPER_BACKGROUND: '#dfdfdf',
  INVESTMENT_ITEM_NAME: '#9a9a9a',
  DISABLED_INPUT_BACKGROUND: '#f2f3f5',
  FORM_TIPS_TEXT: '#ef1c4e'
};

export const LINEAR_GRADIENTS = {
  MAIN_CONTENT_WRAPPER_BACKGROUND: 'linear-gradient(rgb(125, 31, 214), rgb(96, 101, 251))',
  DIALOG_ACTIVE_BUTTON: 'linear-gradient(90deg, #f8da63, #fff3c6)',
  INVESTMENT_BUTTON_BACKGROUND: 'linear-gradient(-40deg, #ff6f00, #ea4879)'
};

export const Z_INDEX = {
  SIDEBAR_CONTAINER: 99,
  DIALOG_CONTAINER: 100
};

export const HEADER_BACKGROUND_COLOR = {
  THEME0: '#251e1e',
  THEME1: '#251e1e'
};
export const HEADER_TEXT_COLOR = {
  THEME0: '#fde68a',
  THEME1: '#fde68a'
};
export const LINK_COLOR = '#61dafb';
export const MAIN_BACKGROUND_WRAPPER = {
  THEME0: '#dfdfdf',
  THEME1: '#dfdfdf'
};
export const MAIN_BACKGROUND_COLOR = {
  THEME0: '#fff',
  THEME1: '#fff'
};
